# permissions for end users to edit keys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: key-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: b2operator
    app.kubernetes.io/part-of: b2operator
    app.kubernetes.io/managed-by: kustomize
  name: key-editor-role
rules:
- apiGroups:
  - b2.issei.space
  resources:
  - keys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - b2.issei.space
  resources:
  - keys/status
  verbs:
  - get
