apiVersion: b2.issei.space/v1alpha1
kind: Bucket
metadata:
  name: my-b2-bucket
spec:
  acl: public
  bucketlifecycle:
    - fileNamePrefix: "/"
      daysFromUploadingToHiding: 2
      daysFromHidingToDeleting: 3
    - fileNamePrefix: "logs"
      daysFromUploadingToHiding: 5
      daysFromHidingToDeleting: 7
  writeConnectionSecretToRef:
    name: my-bucket-credentials
    namespace: default